# This is a basic workflow to help you get started with Actions

name: ⚙️ deployment

# Controls when the workflow will run
on:
  push:
    tags:
      - 'release_*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Run a one-line script
        run: echo Deploy me
